// يمكنك إضافة مفاتيح API الآمنة الخاصة بك هنا لتعمل كأساس في الموقع
export const DEFAULT_EXTRACT_KEYS: string[] = [
    "AIzaSyDpn1LG5j0cKqYV-Ke2Wx61nPjkicAw4MM",
    "AIzaSyBO7JBN61P5AlBKm3eFJbbVt5LGfd4kFlk",
    "AIzaSyCgmGuWLV3KTjmijvpttevhK4YuxmMrQME",
    "AIzaSyD1vJRRdV1PgVyP0ng5Y3v4_MOT-U0veNI",
    "AIzaSyAFt9L7Epb3nt64cS0FYlzl_iYIMewayDg",
    "AIzaSyAdsx_9i-lcklSbyYT07rUdBpV0-VSQXgs",
    "AIzaSyBvVq_dE-42NNNQ67T_H7mMQVG3OL9QrEU",
    "AIzaSyCvu1tmrMRm-XenLA4ZO7e-TH_nvdifgZA",
    "AIzaSyDVDdeZvGwOj7zKqVc0cIAtGF56QPsOcLU",
    "AIzaSyBa2ZJWKTiOy6xQFtB-YfzVuIlJjDjePB8",
    "AIzaSyBx7noLxXCd1XFF7H89H7JUGkx54F3kTko",
    "AIzaSyCNzQ_BF-hYx8Fxr16Px674JJxLttlUXj4",
    "AIzaSyBfnc4pTzm22j-X8Jvk2MAAFk2M7oTTPsU",
    "AIzaSyBB58sXko1hWUfF2iUFNjwJ7Wrk6QzriZE",
    "AIzaSyBL6wwTxBUyclyialBuTQu9kz_AOlk8_R8",
];

export const DEFAULT_CHAT_KEYS: string[] = [
    "AIzaSyByAI-G5-YMXTxWtKl95Hb4vVgWnuzaoDI",
    "AIzaSyDTkoLORzrCO4cTafc7QGlrtGpJ9GoOEJ4",
    "AIzaSyCo_6_eLCNz2OPiBx17TZpdoJJUd4mlDLU",
    "AIzaSyDRwlWRVuUCvj5lAadN_cqux_zN-WCg_ZU",
    "AIzaSyDibCDZ2q95gTP3g2hbhEYDYTmLafhQ9z0",
    "AIzaSyA32uQYMnHnTQiZLvsUcZ-cHIlidpco5eQ",
    "AIzaSyCtFeYF9CCNcZ_Exf6JhE5-arMEEAf20vw",
    "AIzaSyBX3Yk7kSIpdFpsDc7DTFm1oPqa0fVT1Mg",
    "AIzaSyB9yPQUC_HubFxTyuHKjIF9dhKClj6wox4",
    "AIzaSyBjlrlw89-hIdegaPfrKykZeWp_7NjOeoI",
    "AIzaSyDZu5Yz3cn5CTDDTalbTdwIZrlsi4GcL1Y",
    "AIzaSyDzrh8XieUV_pUFBu0fdovFYAUL_r1NDp8",
    "AIzaSyAEhAQpr5Pf3YJ8F--NIyCeczjs3WxAXKo",
    "AIzaSyDMieLans2dIyqIL7WOLC9B-Kt-GS5x0-c",
    "AIzaSyDlpGJe1KPVtj8u6-bb33gzZbYNWlgspKI",
    "AIzaSyDNEEzT1bYMQWIo2ZwkBn5MVJg_6LpZwaY",
    "AIzaSyAe6zhamy6IPPkmGm7Ajhs9Ie4_PY1tlRI",
    "AIzaSyD1CHSQs6vMa0B-sJUXzDoaqqOzwlXvMRI",
    "AIzaSyB0MbzM3xxEvwjVPyivjIxl6_cx2BwZP7c",
    "AIzaSyC7YoZ2SKlVv9gOMoIH4QbeQeKsJ-k5ors",
    "AIzaSyAlRzN5fhGmZWACzhJz6jNOQDMppsAypRE",
    "AIzaSyDLStYZbMJVXFtHLGyCu1PfwEZEgJIF_p8",
    "AIzaSyCRxOAbjZSIEi6iP8Tuxp_bLGQaFz3oyco",
    "AIzaSyBTmXn2XPOEpkLOX5rD0hY90FjtEw3g0_k",
    "AIzaSyCBp6CrIzqYdfo7rrlz5xjHZCsZU6fOweA"
];
